#!/usr/bin/env node
'use strict';
// Generates a 40-node map (the "Photo journal" app) for layout testing. Usage: node tests/gen40.js <dir>
// Creates <dir>/.taskmap via the CLI so the project registers like a real one.
const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const dir = path.resolve(process.argv[2] || 'photo-journal');
fs.mkdirSync(dir, { recursive: true });
const TM = path.join(__dirname, '..', 'bin', 'taskmap');
const run = (args, input) => execFileSync(TM, args, { cwd: dir, input, encoding: 'utf8' }).trim();
if (!fs.existsSync(path.join(dir, '.taskmap', 'map.json'))) run(['init', 'Photo journal', '--goal', 'A phone app that turns the week\'s photos into a short story']);
const w = (t) => ({ what: `${t}.`, why: 'It moves the goal forward.', done_when: `${t} and a friend can confirm it.` });
const items = [];
const add = (key, parent, title, extra) => items.push(Object.assign({ key, parent, title }, w(title), extra || {}));
add('m1', 'n0', 'Decide what a story is');
add('m2', 'n0', 'Import the week\'s photos');
add('m3', 'n0', 'Pick the best shots automatically');
add('m4', 'n0', 'Write the captions');
add('m5', 'n0', 'Lay out the story');
add('m6', 'n0', 'Share it with friends');
add('m7', 'n0', 'Ship to the app store');
add('c1', 'm1', 'Interview five friends');
add('c2', 'm1', 'Write the one-page pitch');
add('c3', 'm1', 'Sketch three story shapes');
add('c4', 'm2', 'Ask for photo permission');
add('c5', 'm2', 'Read the camera roll');
add('c6', 'm2', 'Group photos by day and place');
add('c7', 'm2', 'Throw away screenshots and duplicates');
add('s1', 'c6', 'Cluster by time gaps');
add('s2', 'c6', 'Name places from the map');
add('s3', 'c6', 'Handle photos without location');
add('c8', 'm3', 'Score sharpness and exposure');
add('c9', 'm3', 'Spot faces and smiles');
add('c10', 'm3', 'Keep one of each near-duplicate', { links: ['c7'] });
add('c11', 'm3', 'Let the user veto a pick');
add('c12', 'm4', 'Draft a caption per photo');
add('c13', 'm4', 'Keep the voice consistent across the week');
add('c14', 'm4', 'Let the user rewrite any caption');
add('s4', 'c12', 'Describe what is in the frame');
add('s5', 'c12', 'Add the place and the day');
add('s6', 'c12', 'Keep it under twenty words');
add('c15', 'm5', 'Choose a page template per story shape', { links: ['c3'] });
add('c16', 'm5', 'Flow photos and captions onto pages');
add('c17', 'm5', 'Make the cover page');
add('c18', 'm6', 'Export a video version');
add('c19', 'm6', 'Export a web link that expires');
add('c20', 'm6', 'Send to one friend from the app');
add('c21', 'm7', 'Write the store listing');
add('c22', 'm7', 'Record the preview video', { links: ['c18'] });
add('c23', 'm7', 'Pass the store review');
add('c24', 'm7', 'Set up crash reporting');
add('c25', 'm7', 'Decide the price');
run(['add', '--batch'], JSON.stringify(items));
// Statuses: milestone 1 and 2 done, 3 in progress, one block, one skip, a user-added node, notes and feedback.
const map = JSON.parse(fs.readFileSync(path.join(dir, '.taskmap', 'map.json'), 'utf8'));
const byTitle = Object.fromEntries(Object.values(map.nodes).map((n) => [n.title, n.id]));
const id = (t) => byTitle[t];
for (const t of ['Interview five friends', 'Write the one-page pitch', 'Sketch three story shapes', 'Ask for photo permission', 'Read the camera roll', 'Cluster by time gaps', 'Name places from the map', 'Throw away screenshots and duplicates', 'Score sharpness and exposure']) run(['done', id(t), '--note', `Lives in src/${t.toLowerCase().replace(/[^a-z]+/g, '-')}.js`]);
run(['skip', id('Handle photos without location'), '--reason', 'the phone always records a location in this app']);
run(['done', id('Group photos by day and place')]);
run(['done', id('Decide what a story is')]);
run(['done', id('Import the week\'s photos')]);
run(['start', id('Pick the best shots automatically')]);
run(['start', id('Spot faces and smiles')]);
run(['note', id('Spot faces and smiles'), 'assumed the built-in face detector because it runs offline; say so if wrong']);
run(['block', id('Decide the price'), '--reason', 'waiting on user: free with a one-time unlock, or a subscription? Changes the store listing and the sharing limits.']);
run(['note', 'n0', 'State: shots are being scored. Next: smile detection, then the veto screen. Waiting on you: pricing (n' + String(id('Decide the price')).slice(1) + ').']);
console.log(run(['status']));
